import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartContextProvider } from "@/context/CartContext";
import CartIcon from "@/components/CartIcon";
import ToastProvider from "@/toast/toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider>
          <ToastProvider/>
          <div className="flex flex-row justify-between w-[50%] ml-auto">
            <CartIcon/>
          </div>
        {children}
        </CartContextProvider>
      </body>
    </html>
  );
}
